#!/bin/bash
# YAY 
LINK=https://aur.archlinux.org/yay.git
NAME=$(basename "$LINK" | sed 's/\.git$//')

sudo rm -Rv  ~/git/.git
mkdir ~/git/$NAME
git clone $LINK ~/git/$NAME
cd ~/git/$NAME
makepkg -si


# PACMAN
cd ~/git/conf/
L_MIN=list_pacman_mini.txt
L_START=list_pacman_start.txt

sudo pacman -Rs vi vim --noconfirm 
sudo pacman -Qq > $L_MIN

while IFS= read -r PROGRAM; do
    sudo pacman -S --noconfirm $PROGRAM
done < $L_START

 

 
