#!/bin/bash 
#GRUB management power and boot
GRUB_CF=/etc/default/grub
> $GRUB_CF
echo "GRUB_TIMEOUT=0" >> $GRUB_CF
echo "GRUB_TIMEOUT_STYLE=countdown" >> $GRUB_CF
echo "GRUB_DISABLE_OS_PROBER=false" >> $GRUB_CF
echo "GRUB_ENABLE_CRYPTODISK=y" >> $GRUB_CF
echo "CONFIG_SECURITY_APPARMOR=y" >> $GRUB_CF
echo "CONFIG_AUDIT=y" >> $GRUB_CF

PER="quiet pci=nommconf,noaer,nommconf pcie_aspm=off  audit=1 apparmor=1 security=apparmor"
echo "GRUB_CMDLINE_LINUX_DEFAULT=$PER" >> $GRUB_CF

#APPARMOR settings
PER="landlock,lockdown,yama,integrity,apparmor,bpf"
echo "CONFIG_LSM=$PER" >> $GRUB_CF

systemctl enable auditd
systemctl start auditd
aa-enabled
aa-status

R_CF=/etc/audit/rules.d/quiet.rules
> $R_CF
echo "-A exclude,always -F msgtype=SERVICE_START" >> $R_CF
echo "-A exclude,always -F msgtype=SERVICE_STOP" >> $R_CF
echo "-A exclude,always -F msgtype=BPF" >> $R_CF
echo "-A exclude,always -F exe=/usr/bin/sudo" >> $R_CF

auditctl -a always,exit -F arch=b64 -S openat,truncate -F dir=/etc -F success=0
auditctl -a always,exit -F arch=b64 -F path=/etc/shadow -F perm=wa
auditctl -a exit,always -S chmod
auditctl -w /etc/passwd -p rwxa
auditctl -w /etc/security/

groupadd -r audit
gpasswd -a root audit
gpasswd -a epvre audit
A_CF=/etc/audit/auditd.conf
echo "log_group = audit" >> $A_CF


#WIFI power
W_CF=/etc/modprobe.d/iwlwifi.conf
echo "options iwlmvm power_scheme=1" > $W_CF

#LOG management 
J_CG=/etc/systemd/journald.conf
> $J_CG
echo "[Journal]
Storage=none
SystemMaxUse=250M
SystemKeepFree=125M
SystemMaxFileSize=250M
" >  $J_CG
#sed -i 's/SystemMaxUse=.*/SystemMaxUse=250M/g' $J_CG
#sed -i 's/SystemKeepFree=.*/SystemKeepFree=125M/g' $J_CG
#sed -i 's/SystemMaxFileSize=.*/SystemMaxFileSize=250M/g' $J_CG

systemctl disable systemd-journal*
systemctl stop systemd-journal*
systemctl disable systemd-journald.service
rm -Rv /var/log/journal/*

#COREDUMP off
CORE_CF=/etc/sysctl.d/50-coredump.conf
>$CORE_CF
echo "kernel.core_pattern=/dev/null" > $CORE_CF
sysctl -p $CORE_CF

CORE_CF=/etc/systemd/coredump.conf
sed -i 's/Storage=.*/Storage=none/g' $CORE_CF
echo "Storage=none" >> $CORE_CF

#CORE_CF=/etc/security/limits.conf
#echo "* hard core 0" >> $CORE_CF

rm -Rv /var/lib/systemd/coredump/*

swapoff -va

grub-mkconfig -o /boot/grub/grub.cfg
exit
