#!/bin/bash 
# CLEAR unnecessary
sudo pacman -Rscun vi vim --noconfirm --verbose 

# FREEZE start config
>list_pacman_mini.txt
sudo pacman -Qq >list_pacman_mini.txt  

# INSTALL ALL PACKAGES
sudo pacman -S --needed $(<list_pacman_start.txt) --noconfirm --verbose 


# YAY 
LINK=https://aur.archlinux.org/yay.git
NAME=$(basename "$LINK" | sed 's/\.git$//')

sudo rm -Rv  ~/git/.git
mkdir ~/git/$NAME
git clone $LINK ~/git/$NAME
cd ~/git/$NAME
makepkg -si
yay
