#!/bin/bash 
# CLEAR unnecessary
sudo pacman -Rscun vi vim 

# FREEZE start config

> list_pacman_mini.txt
sudo pacman -Qqv > list_pacman_mini.txt

# INSTALL ALL PACKAGES
sudo pacman -S  --noconfirm --needed list_pacman_start.txt

# YAY 
LINK=https://aur.archlinux.org/yay.git
NAME=$(basename "$LINK" | sed 's/\.git$//')

pacman -S base-devel --noconfirm --needed
cd ~/git
git clone $LINK
cd $NAME
makepkg -si
