#!/bin/bash 

# CLEAR unnecessary
L_MIN=list_pacman_mini.txt
L_START=list_pacman_start.txt
> $OUT

pacman -Rs vi vim --noconfirm 
pacman -Qq >$L_MIN
pacman -S --needed $(<$L_START) --noconfirm --verbose 
rm -Rv  ~/.bash_history

#POWER management 
GRUB_CF=/etc/default/grub
> $GRUB_CF
sed -i 's/GRUB_TIMEOUT=[0-9]*/GRUB_TIMEOUT=0/g' $GRUB_CF
echo "GRUB_TIMEOUT=0" >> $GRUB_CF

sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash udev.log_priprity=3 pci=nommconf,noaer,nommconf pcie_aspm=off"/g' $GRUB_CF
echo "GRUB_CMDLINE_LINUX_DEFAULT="quiet splash udev.log_priprity=3 pci=nommconf,noaer,nommconf pcie_aspm=off\"" >> $GRUB_CF

sed -i 's/GRUB_TIMEOUT_STYLE=.*/GRUB_TIMEOUT_STYLE=countdown/g' $GRUB_CF
echo "GRUB_TIMEOUT_STYLE=countdown" >> $GRUB_CF

sed -i 's/GRUB_DISABLE_OS_PROBER=.*/GRUB_DISABLE_OS_PROBER=false/g' $GRUB_CF
echo "GRUB_DISABLE_OS_PROBER=false" >> $GRUB_CF

#sed -i 's/GRUB_ENABLE_CRYPTODISK=.*/GRUB_ENABLE_CRYPTODISK=y/g' $GRUB_CF
echo "GRUB_ENABLE_CRYPTODISK=y" >> $GRUB_CF

#WIFI power
W_CF=/etc/modprobe.d/iwlwifi.conf
cat >$W_CF<<EOF
options iwlmvm power_scheme=1
EOF

grub-mkconfig -o /boot/grub/grub.cfg

#LOG management 
J_CG=/etc/systemd/journald.conf
sed -i 's/SystemMaxUse=.*/SystemMaxUse=250M/g' $J_CG
sed -i 's/SystemKeepFree=.*/SystemKeepFree=125M/g' $J_CG
sed -i 's/SystemMaxFileSize=.*/SystemMaxFileSize=250M/g' $J_CG
rm -Rv /var/log/journal/*

systemctl disable systemd-journal-flush.service 
systemctl stop systemd-journal-flush.service 
systemctl disable systemd-journald.socket
systemctl stop systemd-journald.socket
systemctl disable systemd-journald-dev-log.socket
systemctl stop systemd-journald-dev-log.socket
systemctl disable systemd-journald.service
systemctl stop systemd-journald.service

#COREDUMP off
CORE_CF=/etc/sysctl.d/50-coredump.conf
>$CORE_CF
echo "kernel.core_pattern=/dev/null" > $CORE_CF
sysctl -p $CORE_CF

CORE_CF=/etc/systemd/coredump.conf
sed -i 's/Storage=.*/Storage=none/g' $CORE_CF

CORE_CF=/etc/security/limits.conf
echo "* hard core 0">>$CORE_CF

rm -Rv /var/lib/systemd/coredump/*

exit
