#!/bin/bash 
  tee /boot/loader/loader.conf < EOF
  timeout=0
  GRUB_CMDLINE_LINUX_DEFAULT="quiet splash pci=noaer"
  EOF
sudo rm -Rv  ~/.bash_history
systemctl disable systemd-journald.service
systemctl stop systemd-journald.service

systemctl disable systemd-journald.socket
systemctl stop systemd-journald.socket

systemctl disable systemd-journald-dev-log.socket
systemctl stop systemd-journald-dev-log.socket

#COREDUMP off
  tee /etc/sysctl.d/50-coredump.conf<EOF
  kernel.core_pattern=/dev/null
  EOF
  sysctl -p /etc/sysctl.d/50-coredump.conf
  
  sed -i '/\[Coredump\]/s/\[Coredump\]/\[Coredump\]\nStorage=none/' /etc/systemd/coredump.conf
  sed -i '/End of file/c\* hard core 0\nEnd of file' /etc/security/limits.conf
  rm -Rv /var/lib/systemd/coredump/*

# CLEAR unnecessary
L_MIN=list_pacman_mini.txt
L_START=list_pacman_start.txt

sudo pacman -Rscun vi vim --noconfirm --verbose 

# FREEZE start config
> $OUT
pacman -Qq >$L_MIN

# INSTALL ALL PACKAGES
sudo pacman -S --needed $(<$L_START) --noconfirm --verbose 


# YAY 
LINK=https://aur.archlinux.org/yay.git
NAME=$(basename "$LINK" | sed 's/\.git$//')

sudo rm -Rv  ~/git/.git
mkdir ~/git/$NAME
git clone $LINK ~/git/$NAME
cd ~/git/$NAME
makepkg -si
yay
