#!/bin/bash 

# CLEAR unnecessary
L_MIN=list_pacman_mini.txt
L_START=list_pacman_start.txt
> $OUT

pacman -Rs vi vim --noconfirm 
pacman -Qq >$L_MIN
pacman -S --needed $(<$L_START) --noconfirm --verbose 
#rm -Rv  ~/.bash_history

#POWER management 
GRUB_CF=/etc/default/grub
> $GRUB_CF
sed -i 's/GRUB_TIMEOUT=[0-9]*/GRUB_TIMEOUT=0/g' $GRUB_CF
echo "GRUB_TIMEOUT=0" >> $GRUB_CF

PER="quiet pci=nommconf,noaer,nommconf pcie_aspm=off"
sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT=$PER/g' $GRUB_CF
echo "GRUB_CMDLINE_LINUX_DEFAULT=$PER" >> $GRUB_CF

sed -i 's/GRUB_TIMEOUT_STYLE=.*/GRUB_TIMEOUT_STYLE=countdown/g' $GRUB_CF
echo "GRUB_TIMEOUT_STYLE=countdown" >> $GRUB_CF

sed -i 's/GRUB_DISABLE_OS_PROBER=.*/GRUB_DISABLE_OS_PROBER=false/g' $GRUB_CF
echo "GRUB_DISABLE_OS_PROBER=false" >> $GRUB_CF

#sed -i 's/GRUB_ENABLE_CRYPTODISK=.*/GRUB_ENABLE_CRYPTODISK=y/g' $GRUB_CF
echo "GRUB_ENABLE_CRYPTODISK=y" >> $GRUB_CF

#WIFI power
W_CF=/etc/modprobe.d/iwlwifi.conf
echo "options iwlmvm power_scheme=1" > $W_CF

#LOG management 
J_CG=/etc/systemd/journald.conf
> $J_CG
echo "[Journal]
Storage=none
SystemMaxUse=250M
SystemKeepFree=125M
SystemMaxFileSize=250M
" >  $J_CG
#sed -i 's/SystemMaxUse=.*/SystemMaxUse=250M/g' $J_CG
#sed -i 's/SystemKeepFree=.*/SystemKeepFree=125M/g' $J_CG
#sed -i 's/SystemMaxFileSize=.*/SystemMaxFileSize=250M/g' $J_CG

systemctl disable systemd-journal*
systemctl stop systemd-journal*
systemctl disable systemd-journald.service
rm -Rv /var/log/journal/*

#COREDUMP off
CORE_CF=/etc/sysctl.d/50-coredump.conf
>$CORE_CF
echo "kernel.core_pattern=/dev/null" > $CORE_CF
sysctl -p $CORE_CF

CORE_CF=/etc/systemd/coredump.conf
sed -i 's/Storage=.*/Storage=none/g' $CORE_CF

#CORE_CF=/etc/security/limits.conf
#echo "* hard core 0" >> $CORE_CF

rm -Rv /var/lib/systemd/coredump/*

grub-mkconfig -o /boot/grub/grub.cfg
exit
