#!/bin/bash
#Drivers Nvidia
  sudo pacman -S --noconfirm --needed nvidia mesa lib32-virtualgl lib32-nvidia-utils primus bumblebee
  sudo gpasswd -a $USER bumblebee 
  sudo pacman -S acpi_call
  modprobe acpi_call
  /usr/share/acpi_call/examples/turn_off_gpu.sh
  /etc/modules-load.d/acpi_call.conf

#Xserver
  sudo pacman -S --noconfirm --needed xorg-server xorg-xinit xorg-xset xorg-xsetroot xorg-xrandr xorg-xrdb glaex2 xterm xorg-xclock xterm xorg-twm

#Nvidia debug
  #!/bin/bash
  # Указываем путь к файлу конфигурации
  config_file="/etc/bumblebee/xorg.conf.nvidia"
  
  # Находим строку "Section "Device""
  start_line=$(grep -n "Section \"Device\"" $config_file | cut -d: -f1)
  
  # Находим строку "EndSection" после строки "Section "Device""
  end_line=$(grep -n "EndSection" $config_file | awk -F: -v start=$start_line '$1 > start {print $1; exit}')
  
  # Вставляем новую настройку перед строкой "EndSection"
  sed -i "${end_line}i\    Option \"HardDPMS\" \"false\"" $config_file

#Start X
  cp /etc/X11/xinit/xinitrc ~/.xinitrc
  startx
  
  
